### PR TITLE
Self Service for MTGGoldfish Scraping

### PR DESCRIPTION
**Pull request by oerlich**
In order to avoid needing to consistently manually update the ALL_DECKS file, I implemented some UI using the multifaced_cards.py and the mtg-goldfish-lists.py scripts (slightly modified) to allow users to scrape the data from MTGGoldfish themselves. This process takes the current ALL_DECKS file and fills the gap between the last month in the record, and the current month. The scraping runs in a background daemon thread so there is no blocking behavior and the application should be otherwise fully functional while the scraping takes place.

Also included some style edits to the code.

Included in this PR is also the latest ALL_DECKS file for 2023-04 and an updated MULTIFACED_CARDS file.

### CODE REVIEW

**Comment by cderickson** [comment]
This is awesome! I'm busy between work and moving at the moment, but I'll make some time this week to check out these changes

**Comment by oerlich** [comment]
If you want to test it you'll have to pull in and replace the ALL_DECKS file in PR with an older version since it won't let you scrape if your database is already up to date with the current month. While testing I used the ALL_DECKS_2023-01 file

**Comment by cderickson** [comment]
I haven't gotten to look at any code yet, just tested it real quickly today. It got stuck partway through the scraping process and just hung there. I'll still probably merge it later because this is a feature I wanted to add anyway and you've already gotten started on it, but I'd want to round out the feature (with things like error handling, and allowing the user to exit out of an in-process update) before adding it to a release.

**Comment by oerlich** [comment]
Hmm weird that it would hang, it appeared to sometimes in my testing but it was just taking a while for a particular month/format combo. Definitely should add some error handling and early termination conditions to it. I didn't get around to them since I just did this as a quick one day project but in a perfect world they'd be there!

**Comment by cderickson** [comment]
Self-update feature being added in next release. Implemented by downloading existing files rather than having the user scrape the data themselves.

**Pull request closed without merging**
